# Data Cleaning

## Oasis Infobyte Internship

Name:Prince Kumar  
Track:  Data Analytics  
Level Level 1  
Task Task 3 - Cleaning Data  

---

## Objective

The objective of this project is to demonstrate professional-level
data cleaning skills by systematically transforming a messy dataset
into a clean and analysis-ready dataset.

The project includes data quality assessment, missing value handling,
duplicate removal, data standardisation, outlier detection, data type
correction, and before-versus-after data quality comparison.

In [1]:
#import library
import pandas as pd
import numpy as np

In [2]:
#upload dataset
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [3]:
# Load raw dataset

df = pd.read_csv("train.csv")

print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Rows:")
display(df.head())

Dataset Shape: (891, 12)

Column Names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Data Types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

First 5 Rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# Check missing values in each column

missing_values = df.isnull().sum()

print("Missing Values Per Column:")
print(missing_values)

Missing Values Per Column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# Calculate missing value percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": missing_percentage.round(2)
})

display(missing_report)

             Missing Values  Missing Percentage
PassengerId               0                0.00
Survived                  0                0.00
Pclass                    0                0.00
Name                      0                0.00
Sex                       0                0.00
Age                     177               19.87
SibSp                     0                0.00
Parch                     0                0.00
Ticket                    0                0.00
Fare                      0                0.00
Cabin                   687               77.10
Embarked                  2                0.22

In [6]:
# Check duplicate rows

duplicate_count = df.duplicated().sum()

print("Number of Duplicate Rows:", duplicate_count)

Number of Duplicate Rows: 0

In [7]:
# Display duplicate rows

duplicate_rows = df[df.duplicated()]

display(duplicate_rows.head(10))

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [8]:
# Check value ranges of numeric columns

numeric_columns = df.select_dtypes(include=np.number).columns

range_report = df[numeric_columns].describe().T[
    ["min", "max", "mean", "50%"]
]

range_report = range_report.rename(columns={
    "50%": "median"
})

display(range_report)

              min       max        mean    median
PassengerId  1.00  891.0000  446.000000  446.0000
Survived     0.00    1.0000    0.383838    0.0000
Pclass       1.00    3.0000    2.308642    3.0000
Age          0.42   80.0000   29.699118   28.0000
SibSp        0.00    8.0000    0.523008    0.0000
Parch        0.00    6.0000    0.381594    0.0000
Fare         0.00  512.3292   32.204208   14.4542

In [9]:
# Check for potentially invalid values

print("Negative Age values:", (df["Age"] < 0).sum())
print("Negative Fare values:", (df["Fare"] < 0).sum())
print("Zero Fare values:", (df["Fare"] == 0).sum())
print("Negative SibSp values:", (df["SibSp"] < 0).sum())
print("Negative Parch values:", (df["Parch"] < 0).sum())

Negative Age values: 0
Negative Fare values: 0
Zero Fare values: 15
Negative SibSp values: 0
Negative Parch values: 0

In [10]:
# Create a data quality report

quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Missing Values": df.isnull().sum().values,
    "Missing Percentage": (
        (df.isnull().sum() / len(df)) * 100
    ).round(2).values
})

display(quality_report)

         Column Data Type  Missing Values  Missing Percentage
0   PassengerId     int64               0                0.00
1      Survived     int64               0                0.00
2        Pclass     int64               0                0.00
3          Name    object               0                0.00
4           Sex    object               0                0.00
5           Age   float64             177               19.87
6         SibSp     int64               0                0.00
7         Parch     int64               0                0.00
8        Ticket    object               0                0.00
9          Fare   float64               0                0.00
10        Cabin    object             687               77.10
11     Embarked    object               2                0.22

In [11]:
# Overall data quality summary

print("Total Rows:", len(df))
print("Total Columns:", len(df.columns))
print("Duplicate Rows:", df.duplicated().sum())

print("\nNumeric Columns:")
print(df.select_dtypes(include=np.number).columns.tolist())

print("\nPotential Range Issues:")
print("Negative Age:", (df["Age"] < 0).sum())
print("Negative Fare:", (df["Fare"] < 0).sum())
print("Zero Fare:", (df["Fare"] == 0).sum())
print("Negative SibSp:", (df["SibSp"] < 0).sum())
print("Negative Parch:", (df["Parch"] < 0).sum())

Total Rows: 891
Total Columns: 12
Duplicate Rows: 0

Numeric Columns:
['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

Potential Range Issues:
Negative Age: 0
Negative Fare: 0
Zero Fare: 15
Negative SibSp: 0
Negative Parch: 0

## Missing Data Handling Strategy

The dataset contains missing values in the Age, Cabin, and Embarked columns.

### Age
Missing Age values will be replaced using the median age.

**Reason:** Age is a numerical variable and the median is less affected by extreme values than the mean.

### Embarked
Missing Embarked values will be replaced using the mode.

**Reason:** Embarked is a categorical variable, so the most frequent category is an appropriate choice.

### Cabin
The Cabin column contains a large number of missing values. Instead of deleting rows, missing Cabin values will be represented as "Unknown".

**Reason:** Deleting rows with missing Cabin values would result in a significant loss of data. The missing Cabin information can also represent the fact that the cabin information was not available.

In [12]:
# Check missing values before cleaning

print("Missing values before handling:")
print(df[["Age", "Cabin", "Embarked"]].isnull().sum())

Missing values before handling:
Age         177
Cabin       687
Embarked      2
dtype: int64

In [13]:
# Handle missing values

# Fill missing Age values with the median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Embarked values with the mode
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Replace missing Cabin values with "Unknown"
df["Cabin"] = df["Cabin"].fillna("Unknown")

print("Missing values after handling:")
print(df[["Age", "Cabin", "Embarked"]].isnull().sum())

Missing values after handling:
Age         0
Cabin       0
Embarked    0
dtype: int64

In [14]:
# Count duplicate rows before removal

duplicates_before = df.duplicated().sum()

print("Duplicate Rows Before Cleaning:", duplicates_before)

Duplicate Rows Before Cleaning: 0

In [15]:
# Remove duplicate rows

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicate Rows After Cleaning:", duplicates_after)

Duplicate Rows After Cleaning: 0

## Duplicate Removal

Duplicate rows were checked before the cleaning process.

All identified duplicate rows were removed using the pandas `drop_duplicates()` method.

The number of duplicate rows before and after removal was recorded to verify that duplicate records were successfully handled.

In [16]:
# Check unique values in categorical columns

print("Sex values:")
print(df["Sex"].unique())

print("\nEmbarked values:")
print(df["Embarked"].unique())

print("\nPclass values:")
print(df["Pclass"].unique())

Sex values:
['male' 'female']

Embarked values:
['S' 'C' 'Q']

Pclass values:
[3 1 2]

In [17]:
# Standardise categorical text values

df["Sex"] = df["Sex"].astype(str).str.strip().str.lower()
df["Sex"] = df["Sex"].replace({
    "male": "Male",
    "female": "Female"
})

df["Embarked"] = df["Embarked"].astype(str).str.strip().str.upper()

print("Standardised Sex values:")
print(df["Sex"].unique())

print("\nStandardised Embarked values:")
print(df["Embarked"].unique())

Standardised Sex values:
['Male' 'Female']

Standardised Embarked values:
['S' 'C' 'Q']

## Data Standardisation

Categorical text values were checked for inconsistent formatting.

The `Sex` column was standardised to consistent values such as `Male` and `Female`.

The `Embarked` column was standardised using uppercase category codes.

The dataset does not contain a date column, so date-format standardisation was not applicable.

In [18]:
# Detect outliers using the IQR method

numeric_columns = ["Age", "Fare", "SibSp", "Parch"]

outlier_report = []

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ]

    outlier_report.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Limit": lower_limit,
        "Upper Limit": upper_limit,
        "Outlier Count": len(outliers)
    })

outlier_report = pd.DataFrame(outlier_report)

display(outlier_report.round(2))

  Column     Q1    Q3    IQR  Lower Limit  Upper Limit  Outlier Count
0    Age  22.00  35.0  13.00         2.50        54.50             66
1   Fare   7.91  31.0  23.09       -26.72        65.63            116
2  SibSp   0.00   1.0   1.00        -1.50         2.50             46
3  Parch   0.00   0.0   0.00         0.00         0.00            213

## Outlier Detection and Handling

The Interquartile Range (IQR) method was used to identify potential outliers in the numeric columns `Age`, `Fare`, `SibSp`, and `Parch`.

A value was considered a potential outlier when it was below Q1 − 1.5 × IQR or above Q3 + 1.5 × IQR.

The identified outliers were reviewed as potential extreme values rather than automatically treating them as data errors.

Extreme values in variables such as Fare, SibSp, and Parch can represent genuine passenger characteristics. Therefore, legitimate extreme observations were retained instead of being removed.

No artificial values were created or removed solely to reduce the number of outliers.

In [19]:
# Correct data types

df["PassengerId"] = df["PassengerId"].astype(str)
df["Survived"] = df["Survived"].astype(int)
df["Pclass"] = df["Pclass"].astype(int)
df["Age"] = df["Age"].astype(float)
df["SibSp"] = df["SibSp"].astype(int)
df["Parch"] = df["Parch"].astype(int)
df["Fare"] = df["Fare"].astype(float)

df["Sex"] = df["Sex"].astype(str)
df["Embarked"] = df["Embarked"].astype(str)
df["Name"] = df["Name"].astype(str)
df["Ticket"] = df["Ticket"].astype(str)
df["Cabin"] = df["Cabin"].astype(str)

print("Data types after correction:")
print(df.dtypes)

Data types after correction:
PassengerId     object
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [20]:
# Final missing value check

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [21]:
# Load original dataset again for before-vs-after comparison

df_before = pd.read_csv("train.csv")

print("Original Rows:", len(df_before))
print("Cleaned Rows:", len(df))

Original Rows: 891
Cleaned Rows: 891

In [22]:
# Create before vs after summary

summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Column Count",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Before Cleaning": [
        len(df_before),
        len(df_before.columns),
        df_before.isnull().sum().sum(),
        df_before.duplicated().sum()
    ],
    "After Cleaning": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

display(summary)

           Metric  Before Cleaning  After Cleaning
0       Row Count              891             891
1    Column Count               12              12
2  Missing Values              866               0
3  Duplicate Rows                0               0

In [23]:
# Save the cleaned dataset

df.to_csv("cleaned_titanic.csv", index=False)

print("Cleaned dataset saved successfully as cleaned_titanic.csv")

Cleaned dataset saved successfully as cleaned_titanic.csv

In [24]:
from google.colab import files

files.download("cleaned_titanic.csv")

## Conclusion

The Titanic dataset was systematically cleaned and transformed into an analysis-ready dataset.

The cleaning process included a complete data quality assessment, missing value handling, duplicate checking and removal, categorical data standardisation, outlier detection using the IQR method, and data type correction.

Missing Age values were handled using median imputation, missing Embarked values were handled using mode imputation, and missing Cabin values were represented as "Unknown" to avoid unnecessary data loss.

Potential outliers were identified using the IQR method and retained when they appeared to represent legitimate passenger characteristics rather than data errors.

The final dataset was validated for missing values, duplicate records, and correct data types and was saved as `cleaned_titanic.csv`.

This process demonstrates a structured and professional approach to preparing real-world data for further analysis.